### default jekyll config variables
title: This Is Site One
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
markdown: kramdown
### multi site build settings
### config variables below are specifically for the multisite setup
### gems are defined in gemfile... in the group:
domain: siteone.com
### destination
destination: _dist/siteOne
### excludes & includes
exclude:
  - Gemfile
  - Gemfile.lock
  - sites/siteTwo
# any folder with and underscore is excluded by default, any folder without is included by default
# included folders with the same name get merged together
### config variables from plugins
# jekyll-pages-directory.rb
pages: sites/siteOne/_pages
# jekyll-define-static-assets-image-paths.rb
# no leading & trailing slashes needed they are already accounted for
# static_assets_images is relative to main directory
# static_assets_images_destination is relative to destination folder
static_assets_images_source: sites/siteOne/_staticAssets/images
static_assets_images_destination: assets/images
